/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  card_image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Issues = {
  _id: string;
  _type: "issues";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coordinators?: string;
  card_image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  pdf?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  articles?: Array<{
    title?: string;
    authors?: string;
    keywords?: string;
    abstract?: string;
    pdf?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    _key: string;
  }>;
};

export type Events = {
  _id: string;
  _type: "events";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  venue?: string;
  location_on_google_maps?: string;
  card_image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  from_date?: string;
  to_date?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = News | SanityImageCrop | SanityImageHotspot | Slug | Issues | Events | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: EventsQuery
// Query: *[_type == "events"] | order(_createdAt desc){    _id,    _createdAt,    title,    "slug": slug.current,    content,    venue,    location_on_google_maps,    "cardImage": card_image{asset->{url}, alt},    from_date,    to_date  }
export type EventsQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  venue: string | null;
  location_on_google_maps: string | null;
  cardImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  from_date: string | null;
  to_date: string | null;
}>;
// Variable: EventBySlugQuery
// Query: *[_type == "events" && slug.current == $slug][0]{    _id,    _createdAt,    title,    "slug": slug.current,    content,    venue,    location_on_google_maps,    "cardImage": card_image{asset->{url}, alt},    from_date,    to_date  }
export type EventBySlugQueryResult = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  venue: string | null;
  location_on_google_maps: string | null;
  cardImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  from_date: string | null;
  to_date: string | null;
} | null;
// Variable: IssuesQuery
// Query: *[_type == "issues"] | order(_createdAt desc){    _id,    _createdAt,    title,    "slug": slug.current,    coordinators,    "cardImage": card_image{asset->{url}, alt},  }
export type IssuesQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  coordinators: string | null;
  cardImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
}>;
// Variable: IssueBySlugQuery
// Query: *[_type == "issues" && slug.current == $slug][0]{    _id,    _createdAt,    title,    "slug": slug.current,    coordinators,    "cardImage": card_image{asset->{url}, alt},    "pdfUrl": pdf.asset->url,        articles[] {      title,      authors,      keywords,      abstract,      "pdfUrl": pdf.asset->url    }  }
export type IssueBySlugQueryResult = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  coordinators: string | null;
  cardImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  pdfUrl: string | null;
  articles: Array<{
    title: string | null;
    authors: string | null;
    keywords: string | null;
    abstract: string | null;
    pdfUrl: string | null;
  }> | null;
} | null;
// Variable: AllNewsQuery
// Query: *[_type == "news"] | order(_createdAt desc){    _id,    _createdAt,    title,    "slug": slug.current,    content,    "cardImage": card_image{asset->{url}, alt},    date  }
export type AllNewsQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  cardImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  date: string | null;
}>;
// Variable: NewsBySlugQuery
// Query: *[_type == "news" && slug.current == $slug][0]{    _id,    _createdAt,    title,    "slug": slug.current,    content,    "cardImage": card_image{asset->{url}, alt},    date  }
export type NewsBySlugQueryResult = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  cardImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  date: string | null;
} | null;
// Variable: NoticesQuery
// Query: *[_type == "notice"] | order(uploadedDate desc){    _id,    name,    "fileUrl": noticeFile.asset->url,    "fileType": noticeFile.asset->extension,    uploadedDate  }
export type NoticesQueryResult = Array<{
  _id: string;
  name: string | null;
  fileUrl: string | null;
  fileType: string | null;
  uploadedDate: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"events\"] | order(_createdAt desc){\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    content,\n    venue,\n    location_on_google_maps,\n    \"cardImage\": card_image{asset->{url}, alt},\n    from_date,\n    to_date\n  }": EventsQueryResult;
    "*[_type == \"events\" && slug.current == $slug][0]{\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    content,\n    venue,\n    location_on_google_maps,\n    \"cardImage\": card_image{asset->{url}, alt},\n    from_date,\n    to_date\n  }": EventBySlugQueryResult;
    "*[_type == \"issues\"] | order(_createdAt desc){\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    coordinators,\n    \"cardImage\": card_image{asset->{url}, alt},\n  }": IssuesQueryResult;
    "*[_type == \"issues\" && slug.current == $slug][0]{\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    coordinators,\n    \"cardImage\": card_image{asset->{url}, alt},\n    \"pdfUrl\": pdf.asset->url,\n    \n    articles[] {\n      title,\n      authors,\n      keywords,\n      abstract,\n      \"pdfUrl\": pdf.asset->url\n    }\n  }": IssueBySlugQueryResult;
    "*[_type == \"news\"] | order(_createdAt desc){\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    content,\n    \"cardImage\": card_image{asset->{url}, alt},\n    date\n  }": AllNewsQueryResult;
    "*[_type == \"news\" && slug.current == $slug][0]{\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    content,\n    \"cardImage\": card_image{asset->{url}, alt},\n    date\n  }": NewsBySlugQueryResult;
    "*[_type == \"notice\"] | order(uploadedDate desc){\n    _id,\n    name,\n    \"fileUrl\": noticeFile.asset->url,\n    \"fileType\": noticeFile.asset->extension,\n    uploadedDate\n  }": NoticesQueryResult;
  }
}
